#!/usr/bin/env python3
"""Generate the buff land-on-other phrase table for the trigger engine.

When you cast a beneficial spell on someone ELSE, the Legends log prints a
third-person "land" line: the target name followed by the spell's
CASTEDOTHERTXT message, e.g.

    Torvin is surrounded by a brief lupine aura.      (Spirit of Wolf)
    Torvin is coated in translucent armor.            (Spirit Armor)

There is no spell name on that line, and the cast line ("You begin casting
Spirit of Wolf.") carries no target — so the engine binds the two together:
a pending bare buff-lane timer (proof I cast it, and the exact spell name)
plus a landing message gives the target. This script emits both the
spell-name -> CASTEDOTHERTXT suffix table and the spell-name -> CASTEDMETXT
self-message table, derived straight from spell_summary.json. Distinct self
and other identities let the same buff run on the player and their pet.

Output: crates/eqlog-triggers/src/buff_lands.rs (checked in; regenerate when
the spell data changes). Run:  python3 tools/spelldata/generate_buff_lands.py
"""
import json
import os
import sys

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
SUMMARY = os.path.join(REPO_ROOT, "fixtures", "local", "spell_summary.json")
OUT = os.path.join(REPO_ROOT, "crates", "eqlog-triggers", "src", "buff_lands.rs")

# Must match generate_packs.py's eligibility so a land entry exists exactly for
# the spells that also get a cast-start timer (the ones that can be pending).
MIN_BUFF_DURATION_SECS = 30
MIN_DEBUFF_DURATION_SECS = 12
PERMANENT_FORMULA = 50


def eligible_buffs(spells):
    return [
        s for s in spells
        if s["beneficial"] and s["classes"]
        and s["duration_formula"] != PERMANENT_FORMULA
        and s["duration_secs_estimate"] >= MIN_BUFF_DURATION_SECS
    ]


def eligible_debuffs(spells):
    return [
        s for s in spells
        if not s["beneficial"] and s["classes"]
        and s["duration_formula"] != PERMANENT_FORMULA
        and s["duration_secs_estimate"] >= MIN_DEBUFF_DURATION_SECS
    ]


def rust_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def land_map(spells):
    """name -> land suffix (dedup by name; same name shares one message)."""
    by_name = {}
    for s in spells:
        msg = (s.get("cast_on_other_message") or "").rstrip("\r\n")
        if not msg:
            continue
        by_name.setdefault(s["name"], msg)
    return by_name


def self_land_map(spells):
    """name -> exact self landing message (dedup by spell name)."""
    by_name = {}
    for s in spells:
        msg = (s.get("cast_on_you_message") or "").rstrip("\r\n")
        if not msg:
            continue
        by_name.setdefault(s["name"], msg)
    return by_name


def table_lines(static_name, doc, by_name):
    rows = sorted(by_name.items(), key=lambda kv: kv[0].lower())
    lines = [f"/// {doc}", f"pub static {static_name}: &[(&str, &str)] = &["]
    for name, msg in rows:
        lines.append(f"    ({rust_str(name)}, {rust_str(msg)}),")
    lines.append("];")
    return lines


def main() -> int:
    with open(SUMMARY, encoding="utf-8") as f:
        spells = json.load(f)["spells"]

    buffs = land_map(eligible_buffs(spells))
    self_buffs = self_land_map(eligible_buffs(spells))
    debuffs = land_map(eligible_debuffs(spells))

    # Coverage stats for the report/comment.
    total_buffs = len(eligible_buffs(spells))
    total_debuffs = len(eligible_debuffs(spells))
    space_form = sum(1 for m in buffs.values() if m.startswith(" "))
    from collections import Counter
    shared = sum(n for m, n in Counter(buffs.values()).items() if n > 1)

    lines = [
        "//! @generated by tools/spelldata/generate_buff_lands.py — do not edit.",
        "//!",
        "//! (spell name, land-on-other message suffix). A spell landing on",
        "//! someone else logs as `<target>` + the spell's CASTEDOTHERTXT, e.g.",
        "//! `Torvin is surrounded by a brief lupine aura.` (Spirit of Wolf) or",
        "//! `A dar ghoul knight yawns.` (Togor's Insects). The engine matches a",
        "//! suffix only for a spell it has a pending bare timer for, so the",
        "//! spell name is always exact. Self landing messages come from the",
        "//! same client data and keep simultaneous self/pet copies distinct.",
        "//!",
        f"//! Coverage: {len(buffs)} of {total_buffs} eligible buffs carry a land",
        f"//! message ({space_form} space-form, rest possessive-form); {shared}",
        "//! share a phrase (disambiguated by which buff is actually pending).",
        f"//! Debuffs: {len(debuffs)} of {total_debuffs} eligible carry one —",
        "//! these bind bare enemy-lane timers (slows, malos — spells with no",
        "//! damage tick to bind on) to their target so death can reap them.",
        "",
    ]
    lines += table_lines(
        "BUFF_LAND_SUFFIXES",
        "`(buff spell name, land-on-other suffix)`, sorted by name.",
        buffs,
    )
    lines += [""]
    lines += table_lines(
        "BUFF_SELF_LAND_MESSAGES",
        "`(buff spell name, exact land-on-self message)`, sorted by name.",
        self_buffs,
    )
    lines.append("")
    lines += table_lines(
        "DEBUFF_LAND_SUFFIXES",
        "`(detrimental spell name, land-on-target suffix)`, sorted by name.",
        debuffs,
    )
    lines.append("")

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"wrote {OUT}", file=sys.stderr)
    print(f"  {len(buffs)} buff land phrases "
          f"({space_form} space-form, {shared} share a phrase)", file=sys.stderr)
    print(f"  {len(debuffs)} debuff land phrases", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
