#!/usr/bin/env python3
"""Generate the buff land-on-other phrase table for the trigger engine.

When you cast a beneficial spell on someone ELSE, the Legends log prints a
third-person "land" line: the target name followed by the spell's
CASTEDOTHERTXT message, e.g.

    Torvin is surrounded by a brief lupine aura.      (Spirit of Wolf)
    Torvin is coated in translucent armor.            (Spirit Armor)

There is no spell name on that line, and the cast line ("You begin casting
Spirit of Wolf.") carries no target — so the engine binds the two together:
a pending bare buff-lane timer (proof I cast it, and the exact spell name)
plus a land line whose suffix matches that spell's CASTEDOTHERTXT gives the
target. This script emits the spell-name -> land-suffix table the engine
needs, derived straight from spell_summary.json (same source the buff/debuff
packs are generated from). Self-casts print CASTEDMETXT ("You feel the spirit
of wolf enter you.") instead, so they never match here and stay self-lane.

Output: crates/eqlog-triggers/src/buff_lands.rs (checked in; regenerate when
the spell data changes). Run:  python3 tools/spelldata/generate_buff_lands.py
"""
import json
import os
import sys

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
SUMMARY = os.path.join(REPO_ROOT, "fixtures", "local", "spell_summary.json")
OUT = os.path.join(REPO_ROOT, "crates", "eqlog-triggers", "src", "buff_lands.rs")

# Must match generate_packs.py's eligibility so a land entry exists exactly for
# the buffs that also get a cast-start timer (the ones that can be pending).
MIN_BUFF_DURATION_SECS = 30
PERMANENT_FORMULA = 50


def eligible_buffs(spells):
    return [
        s for s in spells
        if s["beneficial"] and s["classes"]
        and s["duration_formula"] != PERMANENT_FORMULA
        and s["duration_secs_estimate"] >= MIN_BUFF_DURATION_SECS
    ]


def rust_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> int:
    with open(SUMMARY, encoding="utf-8") as f:
        spells = json.load(f)["spells"]

    # name -> land suffix (dedup by name; same name shares one message).
    by_name = {}
    for s in eligible_buffs(spells):
        msg = (s.get("cast_on_other_message") or "").rstrip("\r\n")
        if not msg:
            continue
        by_name.setdefault(s["name"], msg)

    # Coverage stats for the report/comment.
    total_elig = len(eligible_buffs(spells))
    space_form = sum(1 for m in by_name.values() if m.startswith(" "))
    from collections import Counter
    shared = sum(n for m, n in Counter(by_name.values()).items() if n > 1)

    rows = sorted(by_name.items(), key=lambda kv: kv[0].lower())
    lines = [
        "//! @generated by tools/spelldata/generate_buff_lands.py — do not edit.",
        "//!",
        "//! (buff spell name, land-on-other message suffix). A buff landing on",
        "//! someone else logs as `<target>` + suffix, e.g.",
        "//! `Torvin is surrounded by a brief lupine aura.` The engine matches the",
        "//! suffix only for a spell it has a pending bare buff-lane timer for, so",
        "//! the spell name is always exact and self-casts never match.",
        "//!",
        f"//! Coverage: {len(rows)} of {total_elig} eligible buffs carry a land",
        f"//! message ({space_form} space-form, rest possessive-form); {shared}",
        "//! share a phrase (disambiguated by which buff is actually pending).",
        "",
        "/// `(spell name, land-on-other suffix)`, sorted by name.",
        "pub static BUFF_LAND_SUFFIXES: &[(&str, &str)] = &[",
    ]
    for name, msg in rows:
        lines.append(f"    ({rust_str(name)}, {rust_str(msg)}),")
    lines.append("];")
    lines.append("")

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"wrote {OUT}", file=sys.stderr)
    print(f"  {len(rows)} buff land phrases "
          f"({space_form} space-form, {shared} share a phrase)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
