//! Drops research database: read-only queries over the bundled
//! `data/drops.sqlite` — classic-era PEQ reference data (item → mob → zone
//! drop graph) generated by `tools/dropdata/build_drops_db.py`. This is
//! REFERENCE data for the Drops tab, independent of anything parsed from
//! the player's own log.

use std::path::{Path, PathBuf};

use rusqlite::{Connection, OpenFlags};
use serde::Serialize;
use tauri::path::BaseDirectory;
use tauri::{AppHandle, Manager};

/// The drops database, by precedence:
/// 1. a downloaded data update (`<data_root>/refdata-update/drops.sqlite`,
///    installed by the `data_update_install` command),
/// 2. the bundled `refdata/drops.sqlite` resource in installed builds,
/// 3. the repo's `assets/data/` for dev runs (same pattern as
///    `library::packs_dir`).
/// NOTE: the resource dir is deliberately NOT named `data/` — a writable
/// `data/` beside the executable is the portable-mode marker (see
/// `data_root`), and dev builds copy resources next to the exe, which would
/// silently flip the app into portable mode.
fn db_path(app: &AppHandle) -> Option<PathBuf> {
    let updated = crate::data_root::resolve(app)
        .refdata_update_dir()
        .join("drops.sqlite");
    if updated.is_file() {
        return Some(updated);
    }
    if let Ok(p) = app
        .path()
        .resolve("refdata/drops.sqlite", BaseDirectory::Resource)
    {
        if p.is_file() {
            return Some(p);
        }
    }
    let dev = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../assets/data/drops.sqlite");
    if dev.is_file() {
        Some(dev)
    } else {
        None
    }
}

/// Shared with `spelldb` — the spell/ability reference tables live in the
/// same bundled sqlite file.
pub(crate) fn open(app: &AppHandle) -> Result<Connection, String> {
    let path =
        db_path(app).ok_or("drops database not found (data/drops.sqlite resource missing)")?;
    Connection::open_with_flags(&path, OpenFlags::SQLITE_OPEN_READ_ONLY)
        .map_err(|e| format!("open drops db: {e}"))
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct DropItemRow {
    pub id: i64,
    pub name: String,
    pub itemtype: i64,
    pub slots: i64,
    pub classes: i64,
    pub races: i64,
    pub ac: i64,
    pub hp: i64,
    pub mana: i64,
    pub astr: i64,
    pub asta: i64,
    pub aagi: i64,
    pub adex: i64,
    pub awis: i64,
    pub aint: i64,
    pub acha: i64,
    pub damage: i64,
    pub delay: i64,
    pub magic: i64,
    pub no_drop: i64,
    pub no_rent: i64,
    pub loregroup: i64,
    pub weight: i64,
    pub reqlevel: i64,
    pub haste: i64,
    pub proc_name: Option<String>,
    pub click_name: Option<String>,
    pub worn_name: Option<String>,
    pub focus_name: Option<String>,
    /// Distinct dropping NPCs within the requested era filter.
    pub sources: i64,
    /// Highest-chance dropping mob (zone-filter preferred), and its zone.
    pub top_npc: Option<String>,
    pub top_zone: Option<String>,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct DropSearchResult {
    pub total: i64,
    pub rows: Vec<DropItemRow>,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct DropSource {
    pub npc: String,
    pub level: i64,
    pub zone: Option<String>,
    pub zone_long: Option<String>,
    pub era: Option<i64>,
    pub chance: f64,
    pub spawns: Option<i64>,
}

const ITEM_COLS: &str = "i.id, i.name, i.itemtype, i.slots, i.classes, i.races, i.ac, i.hp, \
     i.mana, i.astr, i.asta, i.aagi, i.adex, i.awis, i.aint, i.acha, \
     i.damage, i.delay, i.magic, i.no_drop, i.no_rent, i.loregroup, \
     i.weight, i.reqlevel, i.haste, i.proc_name, i.click_name, \
     i.worn_name, i.focus_name";

fn item_from_row(row: &rusqlite::Row<'_>, sources: i64) -> rusqlite::Result<DropItemRow> {
    Ok(DropItemRow {
        id: row.get(0)?,
        name: row.get(1)?,
        itemtype: row.get(2)?,
        slots: row.get(3)?,
        classes: row.get(4)?,
        races: row.get(5)?,
        ac: row.get(6)?,
        hp: row.get(7)?,
        mana: row.get(8)?,
        astr: row.get(9)?,
        asta: row.get(10)?,
        aagi: row.get(11)?,
        adex: row.get(12)?,
        awis: row.get(13)?,
        aint: row.get(14)?,
        acha: row.get(15)?,
        damage: row.get(16)?,
        delay: row.get(17)?,
        magic: row.get(18)?,
        no_drop: row.get(19)?,
        no_rent: row.get(20)?,
        loregroup: row.get(21)?,
        weight: row.get(22)?,
        reqlevel: row.get(23)?,
        haste: row.get(24)?,
        proc_name: row.get(25)?,
        click_name: row.get(26)?,
        worn_name: row.get(27)?,
        focus_name: row.get(28)?,
        sources,
        top_npc: None,
        top_zone: None,
    })
}

/// Search/browse the item catalog. `era_max`: 0 classic, 1 +kunark,
/// 2 +velious, 3 everything — an item qualifies when a dropping NPC spawns
/// in a zone of that era or earlier. `slot_mask`/`class_mask` (0 = any)
/// bit-test the item's equip slots / usable classes; `zone` ("" = any)
/// restricts qualifying drop sources to one zone short-name. A name query
/// under 2 characters is allowed when any filter is active (browse mode).
/// `only_sourced` hides items with no qualifying drop source; a zone filter
/// implies it. `sort` is a whitelisted column key.
#[tauri::command]
#[allow(clippy::too_many_arguments)]
pub fn drops_search_items(
    app: AppHandle,
    query: String,
    era_max: i64,
    only_sourced: bool,
    slot_mask: i64,
    class_mask: i64,
    zone: String,
    effect_type: String,
    effect_name: String,
    sort: String,
    descending: bool,
    limit: i64,
    offset: i64,
) -> Result<DropSearchResult, String> {
    let conn = open(&app)?;
    let q = query.trim().to_lowercase();
    let has_filters = slot_mask != 0
        || class_mask != 0
        || !zone.is_empty()
        || !effect_type.is_empty()
        || !effect_name.is_empty();
    if q.len() < 2 && !has_filters {
        return Ok(DropSearchResult {
            total: 0,
            rows: Vec::new(),
        });
    }
    let pattern = if q.is_empty() {
        "%".to_string()
    } else {
        format!("%{}%", q.replace('%', "").replace('_', " "))
    };

    // Column names as they surface from the wrapped select (no `i.` prefix).
    let order_col = match sort.as_str() {
        "ac" => "ac",
        "hp" => "hp",
        "mana" => "mana",
        "damage" => "damage",
        "delay" => "delay",
        "reqlevel" => "reqlevel",
        "sources" => "era_sources",
        "weight" => "weight",
        "haste" => "haste",
        "ratio" => "(CASE WHEN delay > 0 THEN CAST(damage AS REAL) / delay ELSE 0 END)",
        // Text columns: rows without a value sort last in both directions.
        "source" => "top_npc IS NULL, top_npc COLLATE NOCASE",
        "zone" => "top_zone IS NULL, top_zone COLLATE NOCASE",
        "effect" => "effect_any IS NULL, effect_any COLLATE NOCASE",
        _ => "name_lc",
    };
    let order_dir = if descending { "DESC" } else { "ASC" };
    // Whitelisted, never user-interpolated. The kind narrows which effect
    // column must be present; the specific-name test lives in the inner SQL
    // below, guarded by `?6 = ''`, so ?6 is ALWAYS referenced and the bound
    // parameter count stays fixed (SQLite rejects unused bindings).
    let effect_kind_cond = match effect_type.as_str() {
        "proc" => "AND i.proc_name IS NOT NULL",
        "click" => "AND i.click_name IS NOT NULL",
        "worn" => "AND i.worn_name IS NOT NULL",
        "focus" => "AND i.focus_name IS NOT NULL",
        "haste" => "AND i.haste > 0",
        "any" => "AND i.effects_lc != ''",
        _ => "",
    };

    // era_sources / top_source are correlated scalar subqueries; SQLite
    // can't reference a select alias in WHERE, so wrap the aliased select
    // and filter outside. Optional filters use `?N = <neutral> OR …` so the
    // parameter list stays fixed.
    let inner = format!(
        "SELECT {ITEM_COLS}, i.name_lc AS name_lc, \
         (SELECT COUNT(DISTINCT d.npc_id) FROM drops d \
          LEFT JOIN npc_zones nz ON nz.npc_id = d.npc_id \
          LEFT JOIN zones z ON z.short_name = nz.zone \
          WHERE d.item_id = i.id AND (z.era IS NULL OR z.era <= ?1) \
            AND (?5 = '' OR nz.zone = ?5)) AS era_sources, \
         (SELECT n2.name FROM drops d2 \
          JOIN npcs n2 ON n2.id = d2.npc_id \
          LEFT JOIN npc_zones nz2 ON nz2.npc_id = n2.id \
          LEFT JOIN zones z2 ON z2.short_name = nz2.zone \
          WHERE d2.item_id = i.id AND (z2.era IS NULL OR z2.era <= ?1) \
          ORDER BY (CASE WHEN ?5 != '' AND nz2.zone = ?5 THEN 0 ELSE 1 END), \
                   d2.chance DESC, (z2.long_name IS NULL), n2.name ASC, \
                   z2.long_name ASC LIMIT 1) AS top_npc, \
         (SELECT z2.long_name FROM drops d2 \
          JOIN npcs n2 ON n2.id = d2.npc_id \
          LEFT JOIN npc_zones nz2 ON nz2.npc_id = n2.id \
          LEFT JOIN zones z2 ON z2.short_name = nz2.zone \
          WHERE d2.item_id = i.id AND (z2.era IS NULL OR z2.era <= ?1) \
          ORDER BY (CASE WHEN ?5 != '' AND nz2.zone = ?5 THEN 0 ELSE 1 END), \
                   d2.chance DESC, (z2.long_name IS NULL), n2.name ASC, \
                   z2.long_name ASC LIMIT 1) AS top_zone, \
         COALESCE(i.proc_name, i.click_name, i.worn_name, i.focus_name, \
                  CASE WHEN i.haste > 0 \
                       THEN 'haste ' || printf('%03d', i.haste) END) \
             AS effect_any \
         FROM items i \
         WHERE (i.name_lc LIKE ?2 OR (i.effects_lc != '' AND i.effects_lc LIKE ?2)) \
           AND (?3 = 0 OR (i.slots & ?3) != 0) \
           AND (?4 = 0 OR (i.classes & ?4) != 0) {effect_kind_cond} \
           AND (?6 = '' OR i.proc_name = ?6 COLLATE NOCASE \
                OR i.click_name = ?6 COLLATE NOCASE \
                OR i.worn_name = ?6 COLLATE NOCASE \
                OR i.focus_name = ?6 COLLATE NOCASE)"
    );
    let sourced = if only_sourced || !zone.is_empty() {
        "WHERE era_sources > 0"
    } else {
        ""
    };
    let filter_params =
        rusqlite::params![era_max, pattern, slot_mask, class_mask, zone, effect_name];

    let total: i64 = conn
        .query_row(
            &format!("SELECT COUNT(*) FROM ({inner}) {sourced}"),
            filter_params,
            |r| r.get(0),
        )
        .map_err(|e| e.to_string())?;

    let sql = format!(
        "SELECT * FROM ({inner}) {sourced} \
         ORDER BY {order_col} {order_dir}, name_lc ASC LIMIT ?7 OFFSET ?8"
    );
    let mut stmt = conn.prepare(&sql).map_err(|e| e.to_string())?;
    let rows = stmt
        .query_map(
            rusqlite::params![
                era_max,
                pattern,
                slot_mask,
                class_mask,
                zone,
                effect_name,
                limit.clamp(1, 200),
                offset.max(0)
            ],
            |row| {
                // Wrapped-select layout: 0..=28 item cols, 29 name_lc,
                // 30 era_sources, 31 top_npc, 32 top_zone, 33 effect_any.
                let sources: i64 = row.get(30)?;
                let top_npc: Option<String> = row.get(31)?;
                let top_zone: Option<String> = row.get(32)?;
                let mut item = item_from_row(row, sources)?;
                item.top_npc = top_npc;
                item.top_zone = top_zone;
                Ok(item)
            },
        )
        .map_err(|e| e.to_string())?
        .collect::<Result<Vec<_>, _>>()
        .map_err(|e| e.to_string())?;

    Ok(DropSearchResult { total, rows })
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct DropEffect {
    pub name: String,
    /// "proc" | "click" | "worn" | "focus"
    pub kind: String,
    pub items: i64,
}

/// Every distinct item effect (proc/click/worn/focus) with how many items
/// carry it — cached client-side to power the smart-search suggestions and
/// the "Which" combobox. Era-scoped: only effects on items that have a drop
/// source in a zone of `era_max` or earlier count, so a Classic search
/// never offers Luclin-era focus lines.
#[tauri::command]
pub fn drops_effects(app: AppHandle, era_max: i64) -> Result<Vec<DropEffect>, String> {
    let conn = open(&app)?;
    const SOURCED: &str = "EXISTS ( \
        SELECT 1 FROM drops d \
        JOIN npc_zones nz ON nz.npc_id = d.npc_id \
        JOIN zones z ON z.short_name = nz.zone \
        WHERE d.item_id = i.id AND z.era <= ?1)";
    let sql = format!(
        "SELECT name, kind, COUNT(*) AS items FROM ( \
           SELECT i.proc_name AS name, 'proc' AS kind FROM items i \
             WHERE i.proc_name IS NOT NULL AND {SOURCED} \
           UNION ALL SELECT i.click_name, 'click' FROM items i \
             WHERE i.click_name IS NOT NULL AND {SOURCED} \
           UNION ALL SELECT i.worn_name, 'worn' FROM items i \
             WHERE i.worn_name IS NOT NULL AND {SOURCED} \
           UNION ALL SELECT i.focus_name, 'focus' FROM items i \
             WHERE i.focus_name IS NOT NULL AND {SOURCED} \
         ) GROUP BY name, kind ORDER BY items DESC, name ASC"
    );
    let mut stmt = conn.prepare(&sql).map_err(|e| e.to_string())?;
    let rows = stmt
        .query_map(rusqlite::params![era_max], |row| {
            Ok(DropEffect {
                name: row.get(0)?,
                kind: row.get(1)?,
                items: row.get(2)?,
            })
        })
        .map_err(|e| e.to_string())?
        .collect::<Result<Vec<_>, _>>()
        .map_err(|e| e.to_string())?;
    Ok(rows)
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct DropZone {
    pub short_name: String,
    pub long_name: String,
    pub era: i64,
}

/// Zones that actually have dropping NPCs, for the Drops-tab zone filter.
#[tauri::command]
pub fn drops_zones(app: AppHandle) -> Result<Vec<DropZone>, String> {
    let conn = open(&app)?;
    let mut stmt = conn
        .prepare(
            "SELECT z.short_name, z.long_name, z.era FROM zones z \
             WHERE EXISTS (SELECT 1 FROM npc_zones nz WHERE nz.zone = z.short_name) \
             ORDER BY z.long_name ASC",
        )
        .map_err(|e| e.to_string())?;
    let rows = stmt
        .query_map([], |row| {
            Ok(DropZone {
                short_name: row.get(0)?,
                long_name: row.get(1)?,
                era: row.get(2)?,
            })
        })
        .map_err(|e| e.to_string())?
        .collect::<Result<Vec<_>, _>>()
        .map_err(|e| e.to_string())?;
    Ok(rows)
}

/// Every NPC that drops the item (chance descending), one row per
/// (NPC, zone) pairing. NPCs with no known spawn point come back with a
/// null zone regardless of the era filter so a known drop is never hidden.
#[tauri::command]
pub fn drops_item_sources(
    app: AppHandle,
    item_id: i64,
    era_max: i64,
) -> Result<Vec<DropSource>, String> {
    let conn = open(&app)?;
    let mut stmt = conn
        .prepare(
            "SELECT n.name, n.level, nz.zone, z.long_name, z.era, d.chance, nz.spawns \
             FROM drops d \
             JOIN npcs n ON n.id = d.npc_id \
             LEFT JOIN npc_zones nz ON nz.npc_id = n.id \
             LEFT JOIN zones z ON z.short_name = nz.zone \
             WHERE d.item_id = ?1 AND (z.era IS NULL OR z.era <= ?2) \
             ORDER BY d.chance DESC, n.name ASC",
        )
        .map_err(|e| e.to_string())?;
    let rows = stmt
        .query_map(rusqlite::params![item_id, era_max], |row| {
            Ok(DropSource {
                npc: row.get(0)?,
                level: row.get(1)?,
                zone: row.get(2)?,
                zone_long: row.get(3)?,
                era: row.get(4)?,
                chance: row.get(5)?,
                spawns: row.get(6)?,
            })
        })
        .map_err(|e| e.to_string())?
        .collect::<Result<Vec<_>, _>>()
        .map_err(|e| e.to_string())?;
    Ok(rows)
}
